const DB = {
  networks: [
    {id:"SEC-MGMT", name:"安全管理区", cidr:"10.10.100.0/24", gw:"10.10.100.1", biz:"集中安全管理与AI决策", ctrl:"仅管理面访问·双向认证·堡垒机", color:"#a78bfa"},
    {id:"LAN-A", name:"办公区", cidr:"10.10.10.0/24", gw:"10.10.10.1", biz:"普通办公（60台终端+OA）", ctrl:"EDR-A / FW-A / NAC-A；禁止主动访问研发/实验区", color:"#3b82f6"},
    {id:"LAN-B", name:"研发区", cidr:"10.10.20.0/24", gw:"10.10.20.1", biz:"重点研发（40台终端+设计资料+代码仓库）", ctrl:"EDR-B / FW-B / NAC-B / NDR-B；细粒度东西向监测", color:"#22d3ee"},
    {id:"LAN-C", name:"实验区", cidr:"10.10.30.0/24", gw:"10.10.30.1", biz:"实验验证（20台终端+实验数据）", ctrl:"EDR-C / FW-C / NAC-C；默认最小互通", color:"#34d399"},
    {id:"INFRA", name:"公共基础服务区", cidr:"10.10.60.0/24", gw:"10.10.60.1", biz:"统一身份和基础服务", ctrl:"只开放认证/DNS/NTP；管理员访问受控", color:"#fbbf24"},
    {id:"EDGE", name:"边界/上级网络", cidr:"10.10.254.0/24", gw:"—", biz:"模拟外部或上级网络接口", ctrl:"FW-CORE；默认拒绝", color:"#f87171"},
  ],
  assets: [
    {id:"AI-CTRL-01", ip:"10.10.100.20", type:"Server", os:"Linux", svc:"Workflow / Decision Control / Approval", crit:"高", net:"SEC-MGMT", mgr:"SEC-MGMT", health:"ONLINE"},
    {id:"KNOW-01", ip:"10.10.100.21", type:"Server", os:"Linux", svc:"Knowledge Service / Graph DB / PostgreSQL", crit:"高", net:"SEC-MGMT", mgr:"SEC-MGMT", health:"ONLINE"},
    {id:"LLM-01", ip:"10.10.100.22", type:"AI推理节点", os:"Linux", svc:"私有化大模型推理服务", crit:"高", net:"SEC-MGMT", mgr:"AI Decision Service", health:"ONLINE"},
    {id:"SIEM-01", ip:"10.10.100.30", type:"Server", os:"Linux", svc:"日志检索 / 关联 / 告警", crit:"高", net:"SEC-MGMT", mgr:"接收全域日志", health:"ONLINE"},
    {id:"BASTION-01", ip:"10.10.100.40", type:"堡垒机", os:"Linux", svc:"管理员受控接入 / 双向认证", crit:"高", net:"SEC-MGMT", mgr:"SEC-MGMT", health:"ONLINE"},
    {id:"AD-IAM-01", ip:"10.10.60.10", type:"Server", os:"Windows Server 2022", svc:"AD DS / IAM / Kerberos", crit:"关键", net:"INFRA", mgr:"统一域账户与会话控制", health:"ONLINE"},
    {id:"RND-WS-23", ip:"10.10.20.23", type:"Endpoint", os:"Windows 11", svc:"研发工具、EDR Agent", crit:"普通", net:"LAN-B", mgr:"EDR-B、NAC-B", health:"ONLINE", owner:"rnd_chen"},
    {id:"RND-WS-61", ip:"10.10.20.61", type:"Endpoint", os:"Windows 11", svc:"研发终端、EDR Agent", crit:"普通", net:"LAN-B", mgr:"EDR-B、NAC-B", health:"ONLINE", owner:"rnd_li"},
    {id:"RND-FILE-01", ip:"10.10.20.40", type:"Server", os:"Windows Server 2022", svc:"DesignArchiveService / SMB", crit:"关键", net:"LAN-B", mgr:"EDR-B", health:"ONLINE"},
    {id:"RND-GIT-01", ip:"10.10.20.50", type:"Server", os:"Rocky Linux 9", svc:"Git 代码仓库", crit:"高", net:"LAN-B", mgr:"EDR-B / Linux审计", health:"ONLINE"},
    {id:"LAB-SRV-01", ip:"10.10.30.40", type:"Server", os:"Rocky Linux 9", svc:"实验数据服务 LabDataService", crit:"高", net:"LAN-C", mgr:"EDR-C", health:"ONLINE"},
    {id:"OA-APP-01", ip:"10.10.10.50", type:"Server", os:"Rocky Linux 9", svc:"OA 业务应用", crit:"中", net:"LAN-A", mgr:"EDR-A", health:"ONLINE"},
    {id:"UPSTREAM-01", ip:"—（外部）", type:"外部网络", os:"—", svc:"模拟上级网络 / 外部接口", crit:"—", net:"EDGE", mgr:"FW-CORE 默认拒绝", health:"ONLINE"},
  ],
  devices: [
    {id:"FW-CORE", net:"EDGE", caps:["TrafficFilter","NetworkAccessControl"], health:"AVAILABLE"},
    {id:"EDR-A", net:"LAN-A", caps:["EndpointTelemetry","CollectEvidence","EndpointIsolation","RestoreEndpoint"], health:"AVAILABLE"},
    {id:"EDR-B", net:"LAN-B", caps:["EndpointTelemetry","CollectEvidence","EndpointIsolation","RestoreEndpoint"], health:"AVAILABLE"},
    {id:"EDR-C", net:"LAN-C", caps:["EndpointTelemetry","CollectEvidence","EndpointIsolation","RestoreEndpoint"], health:"AVAILABLE"},
    {id:"FW-A", net:"LAN-A", caps:["TrafficFilter","NetworkAccessControl"], health:"AVAILABLE"},
    {id:"FW-B", net:"LAN-B", caps:["TrafficFilter","NetworkAccessControl"], health:"AVAILABLE"},
    {id:"FW-C", net:"LAN-C", caps:["TrafficFilter","NetworkAccessControl"], health:"AVAILABLE"},
    {id:"NAC-A", net:"LAN-A", caps:["LANAccessMediation","QuarantineEndpoint"], health:"AVAILABLE"},
    {id:"NAC-B", net:"LAN-B", caps:["LANAccessMediation","QuarantineEndpoint"], health:"AVAILABLE"},
    {id:"NDR-B", net:"LAN-B", caps:["NetworkMonitoring","IncreaseMonitoring"], health:"AVAILABLE"},
    {id:"AD/IAM-01", net:"INFRA", caps:["AccountControl","SessionTermination","MFAEnforcement"], health:"AVAILABLE"},
    {id:"SIEM-01", net:"SEC-MGMT", caps:["SearchEvidence","Correlation"], health:"AVAILABLE"},
  ],
  missions: [
    {id:"MISSION-RD-DESIGN", name:"重点研发设计任务", svc:"DesignArchiveService", asset:"RND-FILE-01", crit:"关键", interrupt:"原则上不可由AI自动中断", policy:"任何隔离/停服动作必须人工高级审批；一期默认不自动执行"},
    {id:"MISSION-RD-CODE", name:"研发代码协同", svc:"GitService", asset:"RND-GIT-01", crit:"高", interrupt:"短时可接受", policy:"高影响动作需人工审批"},
    {id:"MISSION-LAB-TEST", name:"实验数据任务", svc:"LabDataService", asset:"LAB-SRV-01", crit:"高", interrupt:"按实验窗口配置", policy:"维护窗口外高影响动作需人工批准"},
    {id:"MISSION-OFFICE", name:"办公支撑", svc:"OAService", asset:"OA-APP-01", crit:"中", interrupt:"允许短时降级", policy:"普通审批策略"},
  ],
  /* 全部原始告警 SecurityEvent */
  events: [
    /* INC-01 LAN-B 域账户异常+RDP横向（§22.11） */
    {id:"EVT-EDR-001", src:"EDR-B", type:"SuspiciousProcess", sev:"high", time:"2026-09-18 01:07:42", net:"LAN-B", facts:"asset=RND-WS-23；进程链异常（winword→powershell→rundll32）", meaning:"源终端出现异常终端行为；只作为观察证据", incident:"INC-20260918-01"},
    {id:"EVT-NDR-002", src:"NDR-B", type:"AbnormalConnection", sev:"high", time:"2026-09-18 01:12:03", net:"LAN-B", facts:"src=10.10.20.23 → dst=10.10.20.40；protocol=RDP(3389)", meaning:"源终端向关键文件服务器建立异常RDP连接", incident:"INC-20260918-01"},
    {id:"EVT-IAM-003", src:"AD/IAM", type:"AbnormalLogon", sev:"medium", time:"2026-09-18 01:12:31", net:"INFRA", facts:"account=rnd_chen；target=RND-FILE-01；logon_type=remote；非常用时段", meaning:"同一域账户参与远程登录，会话上下文异常", incident:"INC-20260918-01"},
    /* INC-02 跨网异常通信（§23.2） */
    {id:"EVT-NDR-114", src:"NDR-B", type:"CrossDomainTraffic", sev:"high", time:"2026-09-18 03:41:10", net:"LAN-B→LAN-C", facts:"src=10.10.20.61 → dst=10.10.30.40:8080；超出实验提交白名单", meaning:"跨网段异常通信，非业务基线路径", incident:"INC-20260918-02"},
    {id:"EVT-NDR-115", src:"NDR-B", type:"PortScanning", sev:"high", time:"2026-09-18 03:43:55", net:"LAN-B→LAN-C", facts:"src=10.10.20.61 对 10.10.30.0/24 连续探测 30+ 端口", meaning:"疑似对实验区网段进行服务发现扫描", incident:"INC-20260918-02"},
    {id:"EVT-EDR-118", src:"EDR-B", type:"SuspiciousProcess", sev:"medium", time:"2026-09-18 03:39:20", net:"LAN-B", facts:"asset=RND-WS-61；未知签名工具进程 portscan.exe 一次性执行", meaning:"源终端存在扫描工具执行痕迹", incident:"INC-20260918-02"},
    /* INC-03 域账户暴力破解（§23.1） */
    {id:"EVT-IAM-201", src:"AD/IAM", type:"BruteForceSuspect", sev:"high", time:"2026-09-18 06:12:40", net:"INFRA", facts:"account=rnd_liu；5分钟内 47 次 Kerberos 认证失败（来自 10.10.20.77）", meaning:"疑似域账户密码猜测/暴力破解", incident:"INC-20260918-03"},
    {id:"EVT-IAM-202", src:"AD/IAM", type:"AbnormalAccess", sev:"high", time:"2026-09-18 06:24:18", net:"INFRA", facts:"rnd_liu 认证成功后 10 分钟内访问 RND-GIT-01 / RND-FILE-01 等未授权服务器", meaning:"账户被攻破后越权横向访问", incident:"INC-20260918-03"},
    {id:"EVT-SIEM-207", src:"SIEM-01", type:"CorrelationHit", sev:"medium", time:"2026-09-18 06:26:02", net:"SEC-MGMT", facts:"关联规则 R-CRED-012 命中：暴力破解成功 + 越权访问", meaning:"多源证据支撑账户失陷研判", incident:"INC-20260918-03"},
    /* INC-04 IOC 命中 OA（§23.3） */
    {id:"EVT-TI-009", src:"威胁情报", type:"IOC_HIT", sev:"medium", time:"2026-09-18 07:03:14", net:"LAN-A", facts:"IOC: 45.155.204.[x]（已知C2）命中 OA-APP-01 出站连接", meaning:"已知恶意指标命中内部资产", incident:"INC-20260918-04"},
    {id:"EVT-NDR-011", src:"NDR-A", type:"C2Beacon", sev:"high", time:"2026-09-18 07:05:47", net:"LAN-A→边界", facts:"OA-APP-01 → 45.155.204.[x]:443 周期性外联（beacon间隔约5min）", meaning:"疑似 C2 心跳外联行为", incident:"INC-20260918-04"},
    /* 历史已闭环 */
    {id:"EVT-IAM-087", src:"AD/IAM", type:"PrivilegeEscalation", sev:"high", time:"2026-09-16 09:22:55", net:"INFRA", facts:"account=lab_wang；加入 Domain Admins 组后 10 分钟内移除", meaning:"异常提权操作，疑似账户滥用（已闭环）", incident:"INC-20260916-07"},
    /* 未成案低危 */
    {id:"EVT-EDR-210", src:"EDR-A", type:"SuspiciousProcess", sev:"low", time:"2026-09-18 08:31:00", net:"LAN-A", facts:"asset=OA-APP-01；未知签名进程一次性执行后退出", meaning:"低危孤立告警，未满足成案规则", incident:null},
    {id:"EVT-NDR-233", src:"NDR-B", type:"TrafficSpike", sev:"low", time:"2026-09-18 09:02:11", net:"LAN-B", facts:"10.10.20.18 → RND-GIT-01 流量突增（备份窗口内）", meaning:"符合例行备份基线，未成案", incident:null},
  ],
  /* Incident 事件档案（含 4 个可交互处置场景 + 1 个历史闭环） */
  incidents: [
    {id:"INC-20260918-01", title:"LAN-B 域账户异常与RDP横向访问风险", net:"LAN-B", sev:"高", created:"2026-09-18 01:15:02", scenario:true,
     events:["EVT-EDR-001","EVT-NDR-002","EVT-IAM-003"],
     rule:"源资产一致 + 账户关联 + 10分钟窗口 + 目标资产重叠",
     desc:"研发终端 RND-WS-23 出现异常进程行为，随后以域账户 rnd_chen 向关键设计资料服务器 RND-FILE-01 发起异常 RDP 连接，疑似横向移动，威胁重点研发设计任务。"},
    {id:"INC-20260918-02", title:"LAN-B→LAN-C 跨网异常通信与扫描", net:"LAN-B / LAN-C", sev:"高", created:"2026-09-18 03:46:30", scenario:true,
     events:["EVT-NDR-114","EVT-NDR-115","EVT-EDR-118"],
     rule:"跨域通信不符合业务基线 + 同源资产 + 时间窗口关联",
     desc:"研发终端 RND-WS-61 对实验区网段发起白名单外访问与端口扫描，跨网访问基线为 DENY，疑似违规跨域探测或攻击前置动作，涉及实验数据服务 LAB-SRV-01。"},
    {id:"INC-20260918-03", title:"域账户 rnd_liu 暴力破解与越权访问", net:"INFRA / LAN-B", sev:"高", created:"2026-09-18 06:28:11", scenario:true,
     events:["EVT-IAM-201","EVT-IAM-202","EVT-SIEM-207"],
     rule:"同一账户暴力破解成功 + 后续越权访问 + SIEM 关联规则命中",
     desc:"账户 rnd_liu 在 5 分钟内遭遇 47 次认证失败后成功登录，并越权访问研发区多台服务器，疑似凭证被暴力破解后失陷，波及代码仓库与设计资料服务器。"},
    {id:"INC-20260918-04", title:"OA 服务器命中威胁情报 IOC 疑似 C2 外联", net:"LAN-A", sev:"中", created:"2026-09-18 07:08:47", scenario:true,
     events:["EVT-TI-009","EVT-NDR-011"],
     rule:"IOC命中 + 资产关键度评估 + 外联行为关联",
     desc:"OA-APP-01 出现对已知 C2 指标的周期性外联，威胁情报与 NDR 双源印证。OA 业务为中等重要度、允许短时降级，可走标准 IOC 处置 Playbook。"},
    {id:"INC-20260916-07", title:"域账户 lab_wang 异常提权", net:"INFRA", sev:"高", created:"2026-09-16 09:30:11", scenario:false, stage:8,
     events:["EVT-IAM-087"], rule:"同一账户异常权限变更",
     desc:"账户被临时加入 Domain Admins，研判为内部违规操作；已限制账户并强制MFA，复盘后纳入案例库（历史闭环，只读）。"},
  ],
  missions_impact_note:"Asset → hosts → Service → supports → Mission",
  /* ===== 各场景处置数据（SCEN）===== */
  cases: [
    {id:"CASE-2026-041", title:"域账户异常+RDP横向访问（LAN-B研发区）", date:"2026-09-16", techs:["T1078.002","T1021.001"], result:"CONTAINED", reuse:12, tag:"可推荐案例", sim:0,
     summary:"异常域账户+异常RDP多事件关联成案，采用证据保全优先策略，30分钟内完成遏制，DesignArchive 服务零中断。",
     timeline:[["01:12","EDR/NDR/IAM 三源告警规则关联成案（R-CRED-012）"],["01:15","Analysis Agent 输出研判：凭证泄露+横向移动（HIGH）"],["01:18","生成 4 候选方案，PLAN-C 命中 R-04 被硬规则过滤"],["01:21","人工审批 PLAN-B（证据保全优先），限制窗口调整为 2h"],["01:24","任务 DAG 分域下发：取证→终会话→限账户∥隔离终端→局部控流"],["01:42","效果验证通过：异常活动停止，关键服务正常，转 CONTAINED"]],
     lesson:"证据保全与遏制并行的策略在同类凭证泄露场景可复用；限制窗口 2h 是本次人工修改项，后续同类事件可作为默认值建议。"},
    {id:"CASE-2026-037", title:"跨网段配置漂移导致异常通信", date:"2026-09-17", techs:["T1046"], result:"CONTAINED", reuse:5, tag:"已复盘", sim:0.22,
     summary:"NDR发现白名单外跨域连接，研判为运维配置漂移，优先生成增强监控+局部流量限制方案。",
     timeline:[["10:03","NDR 发现 LAN-B→LAN-C 白名单外连接与端口扫描行为"],["10:06","关联成案，置信度 MEDIUM（攻击 vs 违规工具两假设并存）"],["10:09","按 MEDIUM 置信度原则生成渐进方案（受控阻断+观察）"],["10:20","FW 阻断跨域流量 + NAC 准入降级 + 双域增强监测"],["11:00","确认为运维配置漂移，恢复基线策略，案例沉淀"]],
     lesson:"MEDIUM 置信度下渐进处置避免了误隔离；建议跨域变更增加自动基线核对步骤，从源头减少漂移。"},
    {id:"CASE-2026-029", title:"内部账户违规提权处置", date:"2026-09-10", techs:["T1078"], result:"CONTAINED", reuse:8, tag:"可推荐案例", sim:0,
     summary:"IAM异常提权告警，临时限制账户+强制MFA+人工审查，确认为内部违规，更新Playbook审批级别。",
     timeline:[["09:23","IAM 告警：账户加入 Domain Admins 后 10 分钟内移除"],["09:25","关联 SIEM 认证日志研判：疑似账户滥用（内部违规/失陷两假设）"],["09:28","生成限制账户+强制MFA方案，高影响全域策略被过滤"],["09:35","临时限制账户并通知本人核实，确认为内部违规操作"],["16:00","人工审查闭环，Playbook 审批级别上调，案例沉淀"]],
     lesson:"内部违规与外部失陷的区分依赖人工核实环节；强制 MFA 对高权限账户应作为长期加固项。"},
    {id:"CASE-2026-022", title:"IOC命中标准处置（OA区）", date:"2026-09-05", techs:["T1071.001"], result:"CONTAINED", reuse:15, tag:"可推荐案例", sim:0.1,
     summary:"威胁情报命中普通资产，走快速处置流程：证据收集→流量过滤→独立验证，全程无人工介入高影响动作。",
     timeline:[["14:11","威胁情报 IOC 命中 OA 应用服务器出站连接"],["14:12","NDR beacon 检测印证，双源证据关联成案（HIGH）"],["14:14","标准 Playbook 匹配：取证→阻断 C2 出站→增强监测"],["14:18","FW 阻断外联，EDR 留存 Webshell 排查证据"],["14:40","独立验证：beacon 消失且无新 IOC 命中，转 CONTAINED"]],
     lesson:"普通资产 IOC 命中可走免审批快速通道（无高影响动作）；证据留存为后续取证保留了条件。"},
  ],
  attackKB: [
    {id:"T1078.002", name:"Valid Accounts: Domain Accounts", type:"Sub-technique", parent:"T1078", platform:"Windows/Linux/macOS/ESXi", mitigation:"M1026 / M1018", d3fend:["D3-DAM","D3-MFA","D3-AL","D3-CE/CR"]},
    {id:"T1021.001", name:"Remote Services: Remote Desktop Protocol", type:"Sub-technique", parent:"T1021", platform:"Windows", mitigation:"M1035 / M1042", d3fend:["D3-ST","D3-NI","D3-NTF"], det:"DET0327 / AN0931"},
    {id:"T1046", name:"Network Service Discovery", type:"Technique", parent:"Discovery", platform:"Windows/Linux", mitigation:"—", d3fend:["D3-NTF","D3-NAM"]},
    {id:"T1110.001", name:"Brute Force: Password Guessing", type:"Sub-technique", parent:"T1110", platform:"Windows", mitigation:"M1037 / M1018", d3fend:["D3-AL","D3-MFA","D3-DAM"]},
    {id:"T1071.001", name:"Application Layer Protocol: Web Protocols", type:"Sub-technique", parent:"T1071", platform:"Windows/Linux", mitigation:"M1031 / M1037", d3fend:["D3-NTF","D3-NTA"]},
  ],
  d3fendKB: [
    {id:"D3-DAM", name:"Domain Account Monitoring", cat:"Detect", impl:"SIEM/AD审计：账户变化、异常登录上下文", action:"increase_account_monitoring", product:"SIEM / IAM"},
    {id:"D3-MFA", name:"Multi-factor Authentication", cat:"Harden", impl:"IAM策略：高风险/高权限账户强制MFA", action:"require_mfa（长期加固）", product:"IAM"},
    {id:"D3-AL", name:"Account Locking", cat:"Isolate", impl:"IAM 临时禁用用户账户", action:"restrict_account", product:"AD/IAM"},
    {id:"D3-CE/CR", name:"Credential Eviction / Revocation", cat:"Evict", impl:"重置/吊销凭证流程，默认人工确认", action:"revoke_credential", product:"IAM"},
    {id:"D3-ST", name:"Session Termination", cat:"Isolate", impl:"IAM/AD 强制结束异常会话", action:"terminate_session", product:"AD/IAM"},
    {id:"D3-NAM", name:"Network Access Mediation", cat:"Harden", impl:"NAC 隔离VLAN、端点准入控制", action:"restrict_network_access", product:"NAC"},
    {id:"D3-NI", name:"Network Isolation", cat:"Isolate", impl:"EDR隔离或NAC隔离（不含关键服务器自动隔离）", action:"isolate_endpoint", product:"EDR / NAC"},
    {id:"D3-NTF", name:"Network Traffic Filtering", cat:"Isolate", impl:"FW 局部过滤，参数来自ActionTemplate白名单", action:"apply_network_policy", product:"FW"},
  ],
  rules: [
    {id:"R-01", name:"TargetType", cond:"Action=EndpointIsolation", result:"target 必须为 Endpoint", impl:"JSON Schema + 图查询"},
    {id:"R-02", name:"Capability", cond:"Action 需要某 Capability", result:"目标资产必须 managedBy 能提供该 Capability 的 Product", impl:"Knowledge Service 查询"},
    {id:"R-03", name:"Scope", cond:"Task.network_scope ≠ target.belongsTo", result:"DENY", impl:"Decision Control + Local 二次校验"},
    {id:"R-04", name:"CriticalAsset", cond:"target.criticality=CRITICAL 且 impact=HIGH", result:"要求高级/双人审批；一期默认禁止自动执行", impl:"Policy Engine"},
    {id:"R-05", name:"Rollback", cond:"impact ≥ MEDIUM", result:"必须有 rollback 或明确 manual_restore", impl:"ActionTemplate 约束"},
    {id:"R-06", name:"Evidence", cond:"AI 高风险结论", result:"至少关联一个 Observed Evidence，结论不得写成硬事实", impl:"Analysis Output Schema"},
    {id:"R-07", name:"Expire", cond:"task.expire_at < now", result:"DENY", impl:"Local Execution Service"},
    {id:"R-08", name:"Health", cond:"Capability.health ≠ AVAILABLE", result:"不得生成/执行该动作", impl:"Planning 过滤 + 执行前重检"},
  ],
  policies: [
    {level:"低", example:"增强监控、查询状态、收集非破坏性信息", approval:"可配置自动或单人确认"},
    {level:"中", example:"普通终端隔离、账户临时限制", approval:"人工确认"},
    {level:"高", example:"关键资产断连、大范围网络策略修改", approval:"双人或分级审批"},
    {level:"极高/不可逆", example:"可能导致关键任务中断", approval:"仅人工流程，系统不自动执行"},
  ],
  accessBaseline: [
    {from:"LAN-A", to:"LAN-B / LAN-C", policy:"DENY", note:"仅审批后的特定业务访问"},
    {from:"LAN-B", to:"LAN-C", policy:"DENY", note:"实验提交接口固定主机/端口白名单"},
    {from:"LAN-C", to:"LAN-B", policy:"DENY", note:"默认无主动访问"},
    {from:"各LAN", to:"INFRA", policy:"ALLOW-LIMITED", note:"认证、DNS、NTP 等必要服务"},
    {from:"SEC-MGMT", to:"各LAN", policy:"ALLOW-MGMT", note:"仅安全管理服务身份和堡垒机"},
    {from:"各LAN", to:"SEC-MGMT", policy:"ALLOW-TELEMETRY", note:"日志/告警单向上送，业务访问拒绝"},
  ],
  auditLog: [
    {t:"2026-09-18 07:09:02", who:"Correlation模块", act:"规则命中：形成 Incident INC-20260918-04（IOC+C2外联成案）", lvl:"info"},
    {t:"2026-09-18 06:28:11", who:"Correlation模块", act:"规则命中：形成 Incident INC-20260918-03（暴力破解+越权访问）", lvl:"info"},
    {t:"2026-09-18 03:46:30", who:"Correlation模块", act:"规则命中：形成 Incident INC-20260918-02（跨网异常通信）", lvl:"info"},
    {t:"2026-09-18 01:15:02", who:"Correlation模块", act:"规则命中：形成 Incident INC-20260918-01（3条告警成案）", lvl:"info"},
    {t:"2026-09-18 01:15:03", who:"Security Data Service", act:"原始日志写入对象存储并计算 SHA-256（evi:OBJ-001~003）", lvl:"info"},
    {t:"2026-09-16 09:31:20", who:"Decision Control", act:"拒绝未授权动作：isolate_endpoint(AD-IAM-01) 命中 R-04", lvl:"warn"},
    {t:"2026-09-16 09:35:44", who:"Local Execution LAN-B", act:"验签失败拒绝任务：伪造 signature（TC-05 测试用例）", lvl:"err"},
    {t:"2026-09-15 22:40:11", who:"Effect Verification", act:"IOC处置效果验证通过，Incident 转 CONTAINED", lvl:"ok"},
  ],
};

/* ===== 场景模板：每个可交互 Incident 的研判/方案/任务/验证数据 ===== */
const SCEN = {
"INC-20260918-01":{
  execNets:["LAN-B","INFRA"], approvalLevel:"中（含2项中影响动作）",
  assessment:{
    summary:"研发终端 RND-WS-23 疑似被控，攻击者利用域账户 rnd_chen 通过 RDP 向承载重点研发设计任务的 RND-FILE-01 横向移动。",
    ruleMap:"AbnormalLogon→T1078.002 / AbnormalConnection(RDP)→T1021.001",
    resolve:"10.10.20.23 / EDR device_guid → asset:RND-WS-23（置信度0.98）",
    impact:"RND-FILE-01 hosts DesignArchiveService → supports MISSION-RD-DESIGN（关键）",
    hypotheses:[{h:"H1：rnd_chen 凭证已泄露，攻击者正进行横向移动（主假设）", conf:"HIGH"},{h:"H2：研发人员本人非常用时段远程操作（备选，证据弱）", conf:"LOW"}],
    techniques:[
      {id:"T1078.002", name:"Valid Accounts: Domain Accounts", src:"ATT&CK v19.2", evi:["EVT-IAM-003","EVT-EDR-001"]},
      {id:"T1021.001", name:"Remote Services: Remote Desktop Protocol", src:"ATT&CK v19.2 · 参考 DET0327 / AN0931", evi:["EVT-NDR-002","EVT-IAM-003"]}],
    affected_assets:["RND-WS-23","RND-FILE-01"], affected_services:["DesignArchiveService → MISSION-RD-DESIGN（关键）"],
    evidence:["EVT-EDR-001","EVT-NDR-002","EVT-IAM-003"], confidence:"HIGH",
    missing:["RND-WS-23 内存取证镜像","rnd_chen 近7日完整登录基线"],
    note:"结论保持为 SUPPORTED 假设，不写成硬事实；所有实体与证据引用已通过白名单校验。"},
  plans:[
    {id:"PLAN-A", name:"快速遏制", strategy:"优先阻断扩散，取证后置",
     actions:["terminate_session(rnd_chen/RDP)","restrict_account(rnd_chen, 2h)","isolate_endpoint(RND-WS-23)","increase_monitoring(LAN-B)"],
     impact:"中", scores:{effect:5,biz:3,exec:5,evi:4}, rule:"PASS", ruleNote:"全部动作通过硬规则校验", diff:"安全效果最高，但取证信息可能不完整"},
    {id:"PLAN-B", name:"证据保全优先", strategy:"先取证再遏制，业务影响最小", recommended:true,
     actions:["collect_evidence(RND-WS-23)","terminate_session(rnd_chen/RDP)","restrict_account(rnd_chen, 2h) ∥ isolate_endpoint(RND-WS-23)","apply_network_policy(RND-WS-23↔RND-FILE-01)","verify_effect(INC-20260918-01)"],
     impact:"低-中", scores:{effect:5,biz:4,exec:5,evi:5}, rule:"PASS", ruleNote:"全部动作通过硬规则校验", diff:"安全效果高、业务影响低，系统推荐人工选择"},
    {id:"PLAN-C", name:"隔离目标服务器", strategy:"直接隔离 RND-FILE-01",
     actions:["isolate_endpoint(RND-FILE-01)"],
     impact:"高", scores:{effect:2,biz:1,exec:4,evi:3}, rule:"DENY", ruleNote:"命中硬规则 R-04 CriticalAsset：目标承载 MISSION-RD-DESIGN（关键），一期默认禁止自动执行，不进入审批", diff:"被硬规则过滤，不进入审批链"},
    {id:"PLAN-D", name:"低影响观察", strategy:"增强监控 + 会话审查，暂不隔离",
     actions:["increase_monitoring(LAN-B)","terminate_session(高风险会话)"],
     impact:"低", scores:{effect:2,biz:5,exec:5,evi:4}, rule:"PASS", ruleNote:"全部动作通过硬规则校验", diff:"业务影响最低，但在 0.86 置信度下遏制力度偏弱"}],
  tasks:[
    {id:"T1", tpl:"collect_evidence", target:"RND-WS-23", pre:[], exec:"EDR-B", net:"LAN-B", check:"生成 evidence_ref"},
    {id:"T2", tpl:"terminate_session", target:"rnd_chen / RDP session", pre:["T1"], exec:"AD/IAM-01", net:"INFRA", check:"会话失效"},
    {id:"T3", tpl:"restrict_account", target:"rnd_chen（2小时窗口）", pre:["T2"], exec:"AD/IAM-01", net:"INFRA", check:"限制窗口生效"},
    {id:"T4", tpl:"isolate_endpoint", target:"RND-WS-23", pre:["T1"], exec:"EDR-B", net:"LAN-B", check:"isolation_state=ISOLATED"},
    {id:"T5", tpl:"apply_network_policy", target:"RND-WS-23 ↔ RND-FILE-01 流量", pre:["T2","T4"], exec:"FW-B", net:"LAN-B", check:"策略命中且无新异常RDP"},
    {id:"T6", tpl:"verify_effect", target:"INC-20260918-01", pre:["T3","T4","T5"], exec:"Effect Verification", net:"SEC-MGMT", check:"关键服务正常且异常活动停止"}],
  effectChecks:[
    {item:"源终端隔离", src:"EDR-B", cond:"RND-WS-23 isolation_state = ISOLATED"},
    {item:"异常会话终止", src:"AD/IAM", cond:"原 RDP session 失效，无新异常认证"},
    {item:"异常连接停止", src:"NDR-B / FW-B", cond:"验证窗口内无 10.10.20.23→10.10.20.40 异常RDP连接"},
    {item:"关键业务健康", src:"服务监控", cond:"DesignArchiveService 健康检查正常"},
    {item:"残余风险", src:"Analysis / 规则", cond:"无新的相关高风险事件，Incident 可转 CONTAINED"}],
  caseSummary:"证据保全优先策略：取证→终止会话→限制账户(2h)∥隔离终端→局部流量控制→验证。DesignArchiveService 零中断。人工修改：限制窗口调整为 2h。"},
"INC-20260918-02":{
  execNets:["LAN-B","LAN-C"], approvalLevel:"中（跨域策略变更需两域确认）",
  assessment:{
    summary:"研发终端 RND-WS-61 违反跨网访问基线（LAN-B→LAN-C 默认 DENY），对实验区网段执行服务发现扫描并尝试访问实验数据服务 LAB-SRV-01，疑似攻击前置侦察或违规工具使用。",
    ruleMap:"CrossDomainTraffic / PortScanning→T1046 / 未知工具进程→T1105 辅助证据",
    resolve:"10.10.20.61 / CMDB asset_code → asset:RND-WS-61（置信度0.97）",
    impact:"LAB-SRV-01 hosts LabDataService → supports MISSION-LAB-TEST（高）；当前处于维护窗口外",
    hypotheses:[{h:"H1：终端被植入扫描工具，正在进行横向侦察（主假设）", conf:"MEDIUM"},{h:"H2：研发人员私自使用未授权工具做连通性测试（备选）", conf:"MEDIUM"}],
    techniques:[
      {id:"T1046", name:"Network Service Discovery", src:"ATT&CK v19.2", evi:["EVT-NDR-115","EVT-EDR-118"]},
      {id:"T1105", name:"Ingress Tool Transfer", src:"ATT&CK v19.2（候选）", evi:["EVT-EDR-118"]}],
    affected_assets:["RND-WS-61","LAB-SRV-01"], affected_services:["LabDataService → MISSION-LAB-TEST（高）"],
    evidence:["EVT-NDR-114","EVT-NDR-115","EVT-EDR-118"], confidence:"MEDIUM",
    missing:["RND-WS-61 端口扫描工具样本哈希","实验区最近变更单"],
    note:"置信度 MEDIUM，按方案原则优先增强监控与局部限制，避免直接高影响处置。"},
  plans:[
    {id:"PLAN-A", name:"跨域阻断+源终端隔离", strategy:"立即切断跨域通路并隔离源终端",
     actions:["apply_network_policy(阻断 RND-WS-61 跨域流量)","isolate_endpoint(RND-WS-61)","increase_monitoring(LAN-C)"],
     impact:"中", scores:{effect:5,biz:4,exec:4,evi:3}, rule:"PASS", ruleNote:"全部动作通过硬规则校验", diff:"阻断彻底，但若为误判会影响该研发终端使用"},
    {id:"PLAN-B", name:"受控阻断+持续观察", strategy:"先阻断跨域流量并加强监测，暂不隔离终端", recommended:true,
     actions:["apply_network_policy(RND-WS-61 跨域流量)","restrict_network_access(RND-WS-61 → LAN-C)","increase_monitoring(LAN-B / LAN-C)","verify_effect(INC-20260918-02)"],
     impact:"低", scores:{effect:4,biz:5,exec:5,evi:4}, rule:"PASS", ruleNote:"全部动作通过硬规则校验", diff:"符合 MEDIUM 置信度下的渐进处置原则，系统推荐"},
    {id:"PLAN-C", name:"隔离实验数据服务器", strategy:"直接隔离 LAB-SRV-01 防止被攻击",
     actions:["isolate_endpoint(LAB-SRV-01)"],
     impact:"高", scores:{effect:2,biz:1,exec:4,evi:2}, rule:"DENY", ruleNote:"命中硬规则 R-04：LAB-SRV-01 承载 MISSION-LAB-TEST（高）且维护窗口外，高影响动作需人工高级审批，不进入自动审批链", diff:"被硬规则过滤，不进入审批链"}],
  tasks:[
    {id:"T1", tpl:"collect_evidence", target:"RND-WS-61", pre:[], exec:"EDR-B", net:"LAN-B", check:"生成 evidence_ref（含工具样本哈希）"},
    {id:"T2", tpl:"apply_network_policy", target:"RND-WS-61 → LAN-C 跨域流量", pre:["T1"], exec:"FW-B", net:"LAN-B", check:"跨域流量命中策略被阻断"},
    {id:"T3", tpl:"restrict_network_access", target:"RND-WS-61（NAC 准入降级）", pre:["T1"], exec:"NAC-B", net:"LAN-B", check:"NAC 策略生效"},
    {id:"T4", tpl:"increase_monitoring", target:"LAN-B / LAN-C", pre:["T2","T3"], exec:"NDR-B", net:"LAN-B", check:"监测规则上线并产出遥测"},
    {id:"T5", tpl:"verify_effect", target:"INC-20260918-02", pre:["T4"], exec:"Effect Verification", net:"SEC-MGMT", check:"无新跨域扫描流量"}],
  effectChecks:[
    {item:"跨域流量阻断", src:"FW-B / FW-C", cond:"验证窗口内无 10.10.20.61 → 10.10.30.0/24 连接"},
    {item:"扫描行为停止", src:"NDR-B", cond:"无新增端口探测事件"},
    {item:"源终端受控", src:"NAC-B", cond:"RND-WS-61 处于准入降级策略组"},
    {item:"实验业务健康", src:"服务监控", cond:"LabDataService 健康检查正常"},
    {item:"残余风险", src:"Analysis / 规则", cond:"无新的相关高风险事件"}],
  caseSummary:"跨网异常通信：受控阻断+持续观察策略。阻断跨域流量→NAC准入降级→双域增强监测→验证。符合 MEDIUM 置信度渐进处置原则。"},
"INC-20260918-03":{
  execNets:["INFRA"], approvalLevel:"高（涉及关键身份基础设施）",
  assessment:{
    summary:"域账户 rnd_liu 遭遇暴力破解（5分钟47次失败）后认证成功，并在10分钟内越权访问研发区多台服务器，凭证大概率已失陷，存在持续横向移动风险。",
    ruleMap:"BruteForceSuspect→T1110.001 / AbnormalAccess→T1078 / SIEM关联规则R-CRED-012",
    resolve:"10.10.20.77（攻击源）经 NDR 与 IAM 会话关联定位；rnd_liu → account:LAB:rnd_liu",
    impact:"账户曾访问 RND-GIT-01（MISSION-RD-CODE 高）与 RND-FILE-01（MISSION-RD-DESIGN 关键）",
    hypotheses:[{h:"H1：rnd_liu 凭证被暴力破解攻破，攻击者已入场（主假设）", conf:"HIGH"},{h:"H2：授权用户遗忘密码多次尝试后正常使用（备选，与越权访问矛盾）", conf:"LOW"}],
    techniques:[
      {id:"T1110.001", name:"Brute Force: Password Guessing", src:"ATT&CK v19.2", evi:["EVT-IAM-201"]},
      {id:"T1078", name:"Valid Accounts", src:"ATT&CK v19.2", evi:["EVT-IAM-202","EVT-SIEM-207"]}],
    affected_assets:["AD-IAM-01","RND-GIT-01","RND-FILE-01"], affected_services:["GitService → MISSION-RD-CODE（高）","DesignArchiveService → MISSION-RD-DESIGN（关键）"],
    evidence:["EVT-IAM-201","EVT-IAM-202","EVT-SIEM-207"], confidence:"HIGH",
    missing:["rnd_liu 全部活动会话清单","攻击源 10.10.20.77 终端取证"],
    note:"账户失陷类事件以账户为主实体；处置以会话终止+账户限制+MFA 为主，不动关键服务器。"},
  plans:[
    {id:"PLAN-A", name:"立即账户遏制", strategy:"终止全部会话并临时限制账户",
     actions:["terminate_session(rnd_liu 全部会话)","restrict_account(rnd_liu, 2h)","increase_account_monitoring(rnd_liu)"],
     impact:"中", scores:{effect:5,biz:4,exec:5,evi:5}, rule:"PASS", ruleNote:"全部动作通过硬规则校验", diff:"遏制迅速；若为误判影响该用户短时使用"},
    {id:"PLAN-B", name:"账户遏制+强制MFA加固", strategy:"遏制同时强制多因素认证，防止凭证重放", recommended:true,
     actions:["terminate_session(rnd_liu 全部会话)","restrict_account(rnd_liu, 2h)","require_mfa(rnd_liu 及同组高风险账户)","increase_account_monitoring(域账户异常模式)","verify_effect(INC-20260918-03)"],
     impact:"中", scores:{effect:5,biz:4,exec:4,evi:5}, rule:"PASS", ruleNote:"全部动作通过硬规则校验", diff:"对应 D3-MFA/D3-DAM 防御链路，系统推荐"},
    {id:"PLAN-C", name:"全域认证策略收紧", strategy:"对全域账户强制MFA+锁定策略",
     actions:["require_mfa(全域)","账户锁定阈值全域下调"],
     impact:"高", scores:{effect:3,biz:2,exec:3,evi:4}, rule:"DENY", ruleNote:"命中硬规则 R-04 变体：大范围身份策略修改属高影响动作，需双人分级审批，不进入自动审批链", diff:"被硬规则过滤，不进入审批链"}],
  tasks:[
    {id:"T1", tpl:"increase_account_monitoring", target:"rnd_liu / 域账户异常模式", pre:[], exec:"SIEM-01", net:"INFRA", check:"监测规则产出遥测"},
    {id:"T2", tpl:"terminate_session", target:"rnd_liu 全部活动会话", pre:["T1"], exec:"AD/IAM-01", net:"INFRA", check:"会话全部失效"},
    {id:"T3", tpl:"restrict_account", target:"rnd_liu（2小时窗口）", pre:["T2"], exec:"AD/IAM-01", net:"INFRA", check:"限制窗口生效"},
    {id:"T4", tpl:"require_mfa", target:"rnd_liu 及同组高风险账户", pre:["T2"], exec:"AD/IAM-01", net:"INFRA", check:"MFA 策略生效"},
    {id:"T5", tpl:"verify_effect", target:"INC-20260918-03", pre:["T3","T4"], exec:"Effect Verification", net:"SEC-MGMT", check:"无新异常认证且账户受控"}],
  effectChecks:[
    {item:"会话终止", src:"AD/IAM", cond:"rnd_liu 原有会话全部失效"},
    {item:"账户限制生效", src:"AD/IAM", cond:"2h 限制窗口内无成功认证"},
    {item:"MFA 策略生效", src:"IAM", cond:"目标账户组下次认证需多因素"},
    {item:"无新暴力破解", src:"SIEM-01", cond:"验证窗口内无针对 rnd_liu 的新失败序列"},
    {item:"残余风险", src:"Analysis / 规则", cond:"凭证重置纳入人工流程（D3-CE/CR）"}],
  caseSummary:"账户暴力破解失陷：终止会话→限制账户→强制MFA→域账户监测增强→验证。全程未触碰关键服务器，符合账户主实体处置原则。"},
"INC-20260918-04":{
  execNets:["LAN-A"], approvalLevel:"中（标准IOC Playbook，单人确认）",
  assessment:{
    summary:"OA 应用服务器 OA-APP-01 对已知 C2 指标（威胁情报 IOC：45.155.204.[x]）发起周期性外联，双源证据（威胁情报+NDR beacon 检测）印证，疑似主机已被控制并建立 C2 通道。",
    ruleMap:"IOC_HIT→T1071.001 / C2Beacon→T1071.001（Web Protocols）",
    resolve:"10.10.10.50 / CMDB → asset:OA-APP-01（置信度0.99）",
    impact:"OAService → MISSION-OFFICE（中，允许短时降级）",
    hypotheses:[{h:"H1：OA-APP-01 被植入后门，正与 C2 通信（主假设）", conf:"HIGH"},{h:"H2：供应链更新误连第三方源（备选，与 beacon 周期不符）", conf:"LOW"}],
    techniques:[
      {id:"T1071.001", name:"Application Layer Protocol: Web Protocols", src:"ATT&CK v19.2", evi:["EVT-TI-009","EVT-NDR-011"]}],
    affected_assets:["OA-APP-01"], affected_services:["OAService → MISSION-OFFICE（中）"],
    evidence:["EVT-TI-009","EVT-NDR-011"], confidence:"HIGH",
    missing:["OA-APP-01 Webshell 排查取证","IOC 关联样本HASH"],
    note:"普通资产 IOC 命中走标准 Playbook：证据收集→局部流量过滤→独立验证，无需高影响动作。"},
  plans:[
    {id:"PLAN-A", name:"标准IOC处置Playbook", strategy:"收集证据后阻断C2外联并持续监测", recommended:true,
     actions:["collect_evidence(OA-APP-01)","apply_network_policy(阻断 → 45.155.204.[x] 出站)","increase_monitoring(LAN-A)","verify_effect(INC-20260918-04)"],
     impact:"低", scores:{effect:5,biz:5,exec:5,evi:5}, rule:"PASS", ruleNote:"全部动作通过硬规则校验", diff:"标准流程，业务零感知，系统推荐"},
    {id:"PLAN-B", name:"隔离主机+流量阻断", strategy:"同时隔离 OA-APP-01 彻底切断风险",
     actions:["apply_network_policy(阻断C2外联)","isolate_endpoint(OA-APP-01)"],
     impact:"中", scores:{effect:5,biz:3,exec:5,evi:5}, rule:"PASS", ruleNote:"通过校验，但 OA 隔离影响办公 Mission（允许短时降级），需人工确认", diff:"更彻底但办公OA将短时不可用"},
    {id:"PLAN-C", name:"仅观察", strategy:"只增强监控不阻断",
     actions:["increase_monitoring(LAN-A)"],
     impact:"低", scores:{effect:1,biz:5,exec:5,evi:4}, rule:"PASS", ruleNote:"通过校验，但 HIGH 置信度下仅观察风险过高", diff:"不推荐：C2 通道持续在线"}],
  tasks:[
    {id:"T1", tpl:"collect_evidence", target:"OA-APP-01", pre:[], exec:"EDR-A", net:"LAN-A", check:"生成 evidence_ref"},
    {id:"T2", tpl:"apply_network_policy", target:"OA-APP-01 → 45.155.204.[x] 出站", pre:["T1"], exec:"FW-A", net:"LAN-A", check:"C2 外联被阻断"},
    {id:"T3", tpl:"increase_monitoring", target:"LAN-A / OA-APP-01", pre:["T2"], exec:"SIEM-01", net:"LAN-A", check:"监测规则上线"},
    {id:"T4", tpl:"verify_effect", target:"INC-20260918-04", pre:["T3"], exec:"Effect Verification", net:"SEC-MGMT", check:"beacon 消失且无新IOC命中"}],
  effectChecks:[
    {item:"C2 外联阻断", src:"FW-A / NDR-A", cond:"验证窗口内无 → 45.155.204.[x] 连接"},
    {item:"beacon 消失", src:"NDR-A", cond:"周期性外联行为停止"},
    {item:"主机状态", src:"EDR-A", cond:"Webshell 排查证据已留存"},
    {item:"办公业务健康", src:"服务监控", cond:"OAService 正常响应"},
    {item:"残余风险", src:"Analysis / 规则", cond:"无新 IOC 命中"}],
  caseSummary:"IOC命中标准Playbook：取证→阻断C2出站→增强监测→验证。办公业务零中断，全程无高影响动作。"},
};

/* ===== 本体建模数据（可交互） ===== */
const ONTO = {
  classes: [
    {name:"NetworkDomain", cn:"网络域", props:"domain_id, cidr, security_level", inst:"LAN-A / LAN-B / SEC-MGMT", on:true, core:true},
    {name:"Asset", cn:"资产抽象类", props:"asset_id, hostname, ip, criticality", inst:"全部终端/服务器", on:true, core:true},
    {name:"Endpoint", cn:"终端", props:"os, edr_status, user_owner", inst:"RND-WS-23", on:true, core:true, parent:"Asset"},
    {name:"Server", cn:"服务器", props:"os, service_role, ha_level", inst:"RND-FILE-01", on:true, core:true, parent:"Asset"},
    {name:"SecurityProduct", cn:"安全产品", props:"product_id, scope, health", inst:"EDR-B / FW-B", on:true, core:true},
    {name:"Service", cn:"业务服务", props:"service_id, health, importance", inst:"DesignArchiveService", on:true, core:true},
    {name:"Mission", cn:"任务/使命", props:"mission_id, criticality, owner", inst:"MISSION-RD-DESIGN", on:true, core:true},
    {name:"Account", cn:"账户", props:"account_id, account_type, status, privilege", inst:"rnd_chen", on:true, core:true},
    {name:"SecurityEvent", cn:"规范化安全事件", props:"event_type, time, severity, source_system", inst:"EVT-NDR-002", on:true, core:true},
    {name:"Incident", cn:"安全事件档案", props:"incident_id, status, scope, confidence", inst:"INC-20260918-01", on:true, core:true},
    {name:"Evidence", cn:"证据", props:"evidence_ref, sha256, source, time", inst:"evi:OBJ-003", on:true, core:true},
    {name:"AttackTechnique", cn:"攻击技术", props:"external_id, name, source_version", inst:"T1078.002", on:true, core:true},
    {name:"DefenseTechnique", cn:"防御技术", props:"external_id, name, source_version", inst:"D3-ST", on:true, core:true},
    {name:"Capability", cn:"现场防御能力", props:"capability_id, scope, health, risk", inst:"LAN-B.EndpointIsolation", on:true, core:true},
    {name:"ActionTemplate", cn:"标准动作模板", props:"action_type, target_type, rollback", inst:"isolate_endpoint", on:true, core:true},
    {name:"Policy", cn:"策略", props:"policy_id, condition, effect", inst:"POL-CRITICAL-ASSET-01", on:true, core:true},
    {name:"DefensePlan", cn:"防御方案", props:"plan_id, objective, status", inst:"PLAN-B-v2", on:true, core:true},
    {name:"DefenseAction", cn:"方案动作", props:"action_id, type, target, impact", inst:"ACT-ISOLATE-01", on:true, core:true, parent:"DefensePlan"},
    {name:"DefenseTask", cn:"执行任务", props:"task_id, scope, expire_at, approval_id", inst:"TASK-1004", on:true, core:true},
    {name:"Approval", cn:"审批", props:"approval_id, level, status, approver", inst:"APP-20260918-02", on:true, core:true},
    {name:"ExecutionResult", cn:"执行结果", props:"status, operation_id, evidence_refs", inst:"EXEC-1004", on:true, core:true},
    {name:"EffectReport", cn:"效果报告", props:"expected/observed, residual_risk", inst:"EFF-1004", on:true, core:true},
  ],
  relations: [
    {name:"belongsTo", from:"Asset", to:"NetworkDomain", use:"资产属于哪个网络域", on:true, core:true, feat:"functional（资产单域）· inverse hasAsset"},
    {name:"managedBy", from:"Asset", to:"SecurityProduct", use:"资产被哪个安全产品管理", on:true, core:true, feat:"inverse manages"},
    {name:"hosts", from:"Asset", to:"Service", use:"资产承载服务", on:true, core:true, feat:"inverse hostedOn"},
    {name:"supports", from:"Service", to:"Mission", use:"服务支撑哪个任务", on:true, core:true, feat:"transitive（影响沿服务链传导）"},
    {name:"accesses", from:"Account", to:"Asset", use:"账户访问资产", on:true, core:true, feat:"—"},
    {name:"communicatesWith", from:"Asset", to:"Asset", use:"基线通信关系", on:true, core:true, feat:"symmetric"},
    {name:"affects", from:"SecurityEvent / Incident", to:"Asset", use:"事件影响对象", on:true, core:true, feat:"—"},
    {name:"derivedFrom", from:"SecurityEvent", to:"Evidence", use:"事件来源于证据", on:true, core:true, feat:"基数 1:n · 证据链溯源"},
    {name:"contains", from:"Incident", to:"SecurityEvent", use:"Incident 由哪些事件组成", on:true, core:true, feat:"inverse partOf"},
    {name:"mappedTo", from:"Incident", to:"AttackTechnique", use:"事件研判映射到 ATT&CK", on:true, core:true, feat:"external ref（attack: 命名空间）"},
    {name:"relatedDefense", from:"AttackTechnique", to:"DefenseTechnique", use:"ATT&CK 到 D3FEND 候选关系", on:true, core:true, feat:"external ref（d3f: 命名空间）"},
    {name:"provides", from:"SecurityProduct", to:"Capability", use:"产品提供现场能力", on:true, core:true, feat:"—"},
    {name:"realizedBy", from:"DefenseTechnique", to:"Capability", use:"防御语义在现场如何实现", on:true, core:true, feat:"—"},
    {name:"implementedBy", from:"Capability", to:"ActionTemplate", use:"能力由哪个标准动作实现", on:true, core:true, feat:"—"},
    {name:"targets", from:"DefenseAction", to:"Asset / Account", use:"动作目标", on:true, core:true, feat:"—"},
    {name:"dependsOn", from:"DefenseTask", to:"DefenseTask", use:"任务依赖", on:true, core:true, feat:"irreflexive · 无环（DAG 约束）"},
    {name:"requiresApproval", from:"DefensePlan / Action", to:"Approval", use:"审批约束", on:true, core:true, feat:"—"},
    {name:"produces", from:"DefenseTask", to:"ExecutionResult", use:"执行任务产出结果", on:true, core:true, feat:"—"},
  ],
};
/* ===== 能力问题库（Competency Questions · Ontology 101 / TOVE 方法：本体的设计目标与验收测试；每个类/属性都必须能回溯到某个 CQ） ===== */
const ONTO_CQS=[
  {id:"CQ-01",rank:"P0",q:"LAN-B 中的主机能否被隔离？隔离动作会影响哪些业务服务与使命？",classes:["Endpoint","Capability","ActionTemplate","Service","Mission"],rels:["hosts","supports","implementedBy"],test:"get_available_capabilities(host) → isolate_endpoint",status:"ok",note:"规划页 P1 方案直接消费"},
  {id:"CQ-02",rank:"P0",q:"当前事件映射到哪些 ATT&CK 技术？对应的 D3FEND 防御候选有哪些？",classes:["Incident","AttackTechnique","DefenseTechnique","Capability"],rels:["mappedTo","relatedDefense","realizedBy"],test:"get_attack_context(incident) → get_defense_options(technique)",status:"ok"},
  {id:"CQ-03",rank:"P0",q:"这条告警涉及的资产是谁（跨数据源同一实体）？所属网络域与关键度？",classes:["Asset","NetworkDomain","SecurityEvent","Endpoint"],rels:["belongsTo","affects"],test:"resolve_entity(ip/host/guid) → get_asset_context(asset)",status:"ok"},
  {id:"CQ-04",rank:"P0",q:"隔离 RND-FILE-01 会不会中断关键使命 MISSION-RD-DESIGN？",classes:["Asset","Service","Mission","Policy"],rels:["hosts","supports"],test:"get_mission_impact(asset/action) → POL-CRITICAL-ASSET-01 拦截",status:"ok"},
  {id:"CQ-05",rank:"P1",q:"账户 rnd_chen 被哪些资产使用过？异常会话是否已收敛？",classes:["Account","Asset","SecurityEvent"],rels:["accesses","affects"],test:"get_asset_context(asset).accounts + 会话校验",status:"ok"},
  {id:"CQ-06",rank:"P0",q:"方案中的每个动作是否都有可执行能力与回滚动作？",classes:["DefenseAction","ActionTemplate","Capability","ExecutionResult"],rels:["implementedBy","provides","produces"],test:"get_available_capabilities(target) + rollback 校验（R-05）",status:"ok"},
  {id:"CQ-07",rank:"P1",q:"执行结果与预期效果是否一致？残余风险如何？",classes:["DefenseTask","ExecutionResult","EffectReport"],rels:["produces"],test:"Effect Verification · verify_effect 任务",status:"ok"},
  {id:"CQ-08",rank:"P1",q:"历史上类似事件（同技术 + 同网域）当时是怎么处置的？",classes:["Incident","AttackTechnique","DefensePlan"],rels:["mappedTo","requiresApproval"],test:"find_similar_cases(context) → 案例库",status:"ok"},
  {id:"CQ-09",rank:"P1",q:"跨网访问是否违反访问基线？违规路径经过哪些网络域？",classes:["Asset","NetworkDomain","SecurityEvent"],rels:["belongsTo","communicatesWith"],test:"get_asset_context + accessBaseline 比对",status:"partial",note:"跨域路径推导需图遍历服务，二期接入"},
  {id:"CQ-10",rank:"P1",q:"证据链是否完整？每条研判结论能否追溯到原始证据？",classes:["SecurityEvent","Evidence","Incident"],rels:["derivedFrom","contains"],test:"get_incident_context(incident).evidence",status:"ok"},
  {id:"CQ-11",rank:"P2",q:"两个账户是否属于同一自然人？（跨系统账户归并）",classes:["Account"],rels:["accesses"],test:"—（暂不可回答）",status:"gap",note:"缺 person_of 关系与身份源对接 → 缺口即二期建模任务"},
  {id:"CQ-12",rank:"P2",q:"自动隔离动作在灰度域的成功率与误报率是多少？",classes:["ActionTemplate","ExecutionResult","EffectReport"],rels:["produces"],test:"统计接口（二期）",status:"partial",note:"需积累执行样本后开放"},
];
/* ===== 外部词汇复用与对齐（Reuse before build · 网络安全域主流：STIX 2.1 / ATT&CK / D3FEND / UCO 优先复用，本地仅扩展） ===== */
const ONTO_ALIGN=[
  {cls:"AttackTechnique",ext:"MITRE ATT&CK（attack: 命名空间）",how:"复用",why:"不重新建模，直接引用 external_id（T1078.002 等），版本锁定 v19.2"},
  {cls:"DefenseTechnique",ext:"D3FEND Ontology（d3f: 命名空间）",how:"复用",why:"防御技术及推导关系沿用 D3FEND v1.6.0"},
  {cls:"Asset",ext:"STIX 2.1 infrastructure / OpenCTI",how:"扩展",why:"SDO 缺 network_scope 与关键度，扩展 asset_code 强标识与域约束"},
  {cls:"Endpoint",ext:"STIX 2.1 infrastructure-type=host",how:"复用+扩展",why:"EDR 状态/属主为现场属性"},
  {cls:"Account",ext:"STIX 2.1 user-account",how:"复用+扩展",why:"加 AD objectGUID 强标识，支撑 CQ-03 实体解析"},
  {cls:"SecurityEvent",ext:"STIX 2.1 observed-data / OpenCTI Sighting",how:"扩展",why:"规范化告警 = 原始观测 + 解析后语义（event_type/severity）"},
  {cls:"Evidence",ext:"STIX 2.1 observed-data（evi: 命名空间）",how:"扩展",why:"加 sha256 与来源系统，满足 CQ-10 证据链溯源"},
  {cls:"Capability",ext:"STIX 2.1 course-of-action / UCO",how:"扩展",why:"健康度、风险与执行端为现场注册属性"},
  {cls:"NetworkDomain",ext:"STIX 2.1 infrastructure-type=network（参考）",how:"扩展",why:"多局域网隔离边界是本系统核心约束"},
  {cls:"Mission",ext:"—（无对应标准词汇）",how:"新建",why:"业务使命为本单位特有概念，影响分析的核心"},
  {cls:"DefensePlan",ext:"—（无对应标准词汇）",how:"新建",why:"决策过程对象，版本链与审批锚点"},
];
/* ===== 类层次（subClassOf · 抽象层不实例化；永久类别建子类，角色与上下文用关系 —— Ontology 101 原则④） ===== */
const ONTO_HIER=[
  {abs:"网络基础设施",c:"#22d3ee",kids:[{n:"NetworkDomain"},{n:"Asset",kids:["Endpoint","Server"]}]},
  {abs:"业务对象",c:"#fb923c",kids:[{n:"Service"},{n:"Mission"}]},
  {abs:"行为主体",c:"#38bdf8",kids:[{n:"Account"}]},
  {abs:"事件",c:"#fbbf24",kids:[{n:"SecurityEvent"},{n:"Incident"}]},
  {abs:"知识与能力",c:"#34d399",kids:[{n:"Evidence"},{n:"AttackTechnique"},{n:"DefenseTechnique"},{n:"Capability"},{n:"ActionTemplate"}]},
  {abs:"决策与控制",c:"#a78bfa",kids:[{n:"Policy"},{n:"DefensePlan",kids:["DefenseAction"]},{n:"DefenseTask"},{n:"Approval"},{n:"ExecutionResult"},{n:"EffectReport"}]},
];

/* ===== 图谱构建数据（可交互） ===== */
const GRAPH = {
  sources: [
    {id:"cmdb", name:"CMDB 资产主数据", detail:"asset_code, hostname, ip, biz_service", nodes:11, edges:18, weight:"全量基线+每日增量", status:"idle"},
    {id:"ad", name:"AD / IAM", detail:"objectGUID, samAccountName, group, logon", nodes:36, edges:74, weight:"全量基线+事件驱动", status:"idle"},
    {id:"edr", name:"EDR", detail:"device_guid, host, alert, isolation_state", nodes:14, edges:41, weight:"增量事件流", status:"idle"},
    {id:"ndr", name:"NDR", detail:"src_ip, dst_ip, protocol, session_id", nodes:9, edges:127, weight:"动态边（TTL 24h）", status:"idle"},
    {id:"fw", name:"Firewall", detail:"src/dst/port/action/policy_id", nodes:6, edges:58, weight:"基线访问+动作验证", status:"idle"},
    {id:"attack", name:"ATT&CK v19.2 STIX", detail:"Technique / Tactic / Detection / Mitigation", nodes:812, edges:1643, weight:"固定版本离线导入", status:"idle"},
    {id:"d3fend", name:"D3FEND v1.6.0", detail:"Defense Technique + full mappings", nodes:438, edges:921, weight:"固定版本离线导入", status:"idle"},
  ],
  mapping: [
    {src:"CMDB", fields:"asset_code, hostname, ip, biz_service", target:"Asset; Asset-hosts-Service", note:"资产主数据优先作为 canonical 基准"},
    {src:"AD/IAM", fields:"objectGUID, samAccountName, group", target:"Account; Account-accesses-Asset", note:"SID/objectGUID 作为强标识"},
    {src:"EDR", fields:"device_guid, host, alert", target:"Endpoint, SecurityEvent, managedBy", note:"原始进程日志不入图，只留证据引用"},
    {src:"NDR", fields:"src_ip, dst_ip, protocol, session_id", target:"Connection; communicatesWith", note:"连接按时间窗生成动态边"},
    {src:"Firewall", fields:"src/dst/port/action/policy_id", target:"NetworkPolicy / Connection", note:"用于基线访问和动作效果验证"},
    {src:"ATT&CK STIX 2.1", fields:"attack-pattern / relationship", target:"AttackTechnique / Tactic / Detection*", note:"固定 v19.2 版本包"},
    {src:"D3FEND", fields:"TTL / full-mappings", target:"DefenseTechnique + ATT&CK关系", note:"v1.6.0 并标记 inferred 属性"},
    {src:"Capability Registry", fields:"product, action, scope, health", target:"SecurityProduct-provides-Capability", note:"本地可执行性权威来源"},
  ],
  erDemo: {
    inputs: [
      {src:"CMDB", id:"asset_code=RND-WS-23"},
      {src:"EDR", id:"device_guid=8f3a-92c1-77de"},
      {src:"NDR", id:"ip=10.10.20.23"},
      {src:"IAM", id:"hostname=DEV-PC-023"},
    ],
    strong:"CMDB asset_code + EDR device_guid（强标识）",
    weak:"IP / hostname（弱标识辅助，域约束 LAN-B）",
    result:"asset:RND-WS-23", confidence:0.98,
  },
};

/* ===== 导出（供 engine.js 导入）===== */
export { DB, SCEN, ONTO, ONTO_CQS, ONTO_ALIGN, ONTO_HIER, GRAPH };
